version: '3.8'

services:
  app:
    build:
      context: .          # Usa o Dockerfile do diretório atual
    container_name: tellover_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - tellover
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: tellover_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tellover
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tellover

networks:
  tellover:

volumes:
  dbdata:
